package jabratech:component-historical-volatility;


interface historical-volatility {
    get-historical-volatility: func(currency: string, start_date: string, end_date: string) -> result<f64, string>;
}

world component-historical-volatility {
    // TODO: Import wasmcloud postgres

    export historical-volatility;
}